package com.comtec.radiologger.model;

public enum MessageTypes {
	START_SCAN,
	STOP_SCAN,
	SCANNED_NEIGHBOURS,
	OPERATOR,
	LOCATION_NAME,
	LOCATION_NAMES,
	CONFIGFILE,
	REFRESH_TIME,
	CLEAR_DB,
	NETWORKTYPE,
	CELLID,
	RSSI,
	FRAGMENT_READY,
	SCAN_ACTIVE,
	CELL_DETECTED,
	LOCATIONCHANGE,
	PLUGINS,
	CELL_CORRECTION,
	QUERY_DBCELLS;
}